name: Build

on:
    push:
        branches:   [ master, development ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
              os: [ubuntu-20.04, macOS-latest, windows-latest]
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-python@v2
          with:
            python-version: 3.7
        - name: Install tools
          if: ${{ matrix.os == 'ubuntu-20.04' }}
          run: | 
            sudo apt-get update
            sudo apt-get install libx11-xcb-dev -y
            sudo apt-get install libxcb*-dev -y
            sudo apt-get install pkg-config -y
            sudo apt-get install mesa-common-dev -y
            sudo apt-get install libgl-dev -y
            sudo apt-get install libglx-dev -y
        - uses: actions/cache@v2
          id: build_cache
          env:
            cache-name: cache-build
          with:
            path: 
              ./build
            key: ${{ matrix.os }}-build-${{ hashFiles('wscript', 'lib', 'tools') }}
            restore-keys: |
                ${{ matrix.os }}-build-
        - name: Build
          if: steps.build_cache.outputs.cache-hit != 'true'
          run: |
            python waf configure build
