name: Build

on:
    push:
        branches:   [ master, development ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
              os: [ubuntu-latest, macOS-latest, windows-latest]
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install tools
          if: ${{ matrix.os == 'ubuntu-latest' }}
          run: | 
            sudo apt-get update
            sudo apt-get install libx11-xcb-dev -y
            sudo apt-get install libxcb*-dev -y
            sudo apt-get install pkg-config -y
        - uses: actions/cache@v2
          env:
            cache-name: cache-build
          with:
            path: ./build
            key: ${{ matrix.os }}-build-${{ hashFiles('wscript') }}
            restore-keys: |
                ${{ matrix.os }}-build-
        - name: Build 
          run: |
            python waf configure
            python waf build_package 
        - uses: actions/upload-artifact@v2
          with:
            name: 'Distributions'
            path: ${{ github.workspace }}/build/fundament-*.tar.gz

