name: Build Base (linux)

on:
    push:
        branches:   [ master, development ]

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
              os: [ubuntu-latest, macOS-latest, windows-latest]
        steps:
        - uses: actions/checkout@v2
        - name: Install tools
          if: ${{ matrix.os == 'ubuntu-latest' }}
          run: | 
            sudo apt-get update
            sudo apt-get install libx11-xcb-dev -y
            sudo apt-get install libxcb*-dev -y
            sudo apt-get install pkg-config -y
        - uses: actions/cache@v2
          env:
            cache-name: cache-build
          with:
            path: ./build
            key: ${{ matrix.os }}-build-${{ hashFiles('wscript') }}
            restore-keys: |
                ${{ matrix.os }}-build-
        - name: Build 
          if: ${{ matrix.os != 'windows-latest' }}
          run: |
            python3 waf configure
            python3 waf build_package
        - name: Build on windows
          if: ${{ matrix.os == 'windows-latest' }}
          run: |
            python waf configure
            python waf build_pacakge

